kind: pipeline
type: docker
name: MPN-latest

steps:
- name: pull 
  image: omerxx/drone-ecr-auth
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-complete:2020-06-08

- name: R40
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-complete:2020-06-08"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/4.0"
  commands:
  - /opt/R/4.0.1/bin/R -e "devtools::install_deps(upgrade = 'never')"
  - /opt/R/4.0.1/bin/R -e "devtools::test()"
  - /opt/R/4.0.1/bin/R -e "devtools::check()"
  depends_on:
  - pull
- name: R36
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-complete:2020-06-08"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/3.6"
  commands:
  - /opt/R/3.6.3/bin/R -e "devtools::install_deps(upgrade = 'never')"
  - /opt/R/3.6.3/bin/R -e "devtools::test()"
  - /opt/R/3.6.3/bin/R -e "devtools::check()"
  depends_on:
  - R40
  
volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock

---

kind: pipeline
type: docker
name: cran-latest

steps:
- name: pull 
  image: omerxx/drone-ecr-auth
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:cran-latest

- name: R40
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:cran-latest"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/4.0"
  commands:
  - /opt/R/4.0.1/bin/R -e "devtools::install_deps(upgrade = 'never')"
  - /opt/R/4.0.1/bin/R -e "devtools::test()"
  - /opt/R/4.0.1/bin/R -e "devtools::check()"
  depends_on:
  - pull
- name: R36
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:cran-latest"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/3.6"
  commands:
  - /opt/R/3.6.3/bin/R -e "devtools::install_deps(upgrade = 'never')"
  - /opt/R/3.6.3/bin/R -e "devtools::test()"
  - /opt/R/3.6.3/bin/R -e "devtools::check()"
  depends_on:
  - R40
  
volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock


---

kind: pipeline
type: docker
name: MPN-oldest
depends_on:
- MPN-latest

steps:
- name: pull 
  image: omerxx/drone-ecr-auth
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:2020-03-24

- name: R40
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:2020-03-24"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/4.0"
  commands:
  - /opt/R/4.0.1/bin/R -e "devtools::install_deps(upgrade = 'never')"
  - /opt/R/4.0.1/bin/R -e "devtools::test()"
  - /opt/R/4.0.1/bin/R -e "devtools::check()"
  depends_on:
  - pull
- name: R36
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:2020-03-24"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/3.6"
  commands:
  - /opt/R/3.6.3/bin/R -e "devtools::install_deps(upgrade = 'never')"
  - /opt/R/3.6.3/bin/R -e "devtools::test()"
  - /opt/R/3.6.3/bin/R -e "devtools::check()"
  depends_on:
  - R40
  
volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
